# Generated by Django 3.0.2 on 2020-02-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youglish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youglishmodel',
            name='language',
            field=models.CharField(default='english', max_length=15),
        ),
    ]
